name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm run start
          browser: chrome
          headed: true