name: "🚀 release"

on:
  release:
    types: [published]

permissions:
    id-token: write
    contents: read

jobs:
    release:
        name: 🚀 release
        runs-on: ubuntu-latest
        steps:
            - name: 📚 checkout
              uses: actions/checkout@v4.1.7
            - name: 🟢 node
              uses: actions/setup-node@v4
              with:
                  node-version: 22.14.0
                  registry-url: https://registry.npmjs.org
            - name: 🚀 publish
              run: npm publish --access public --provenance